title: douglasjam
description: >- # this means to ignore newlines until "baseurl:"
  Trying to express my thoughts and findings to the internet, you may find something useful for you

email:
github_username: douglasjam
repository: "douglasjam/douglasjam.github.io"
minimal_mistakes_skin: "default"

search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "douglasjam"
  avatar : "assets/images/avatar.png"
  bio    : >-
    Father, husband and Christian.<br />
    Software Developer<br />
    Automation enthusiast<br />
    Likes 🥋 🚴 ‍🎣 🧑‍🌾 🍔
  location: "Hamburg, Germany"
  born_at: "Itaúna, Brazil"
  work_skills: "PHP, Symfony, VueJS, Mongo"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/douglasjam/"
    - label: "Strava"
      icon: "fab fa-fw fa-strava orange"
      url: "https://www.strava.com/athletes/douglasjam"

sidebar:
  - title: "A"
  - title: "b"
#  - title: "Title"
#    image: "/assets/images/your-image.jpg"
#    image_alt: "image"
#    text: "Some text here."
#  - title: "Another Title"
#    text: "More text here."
#    nav: sidebar-sample

footer:
  links:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

atom_feed:
  hide: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-78566019-1"
    anonymize_ip: true
